apiVersion: v1
kind: Service
metadata:
  name: myapp-pod-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: myapp-pod
  ports:
    - name: http
      port: 80 # Service port
      targetPort: 80 # Container port