apiVersion: v1
kind: Service
metadata:
  name: replicaset-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: my-helloworld
  ports:
    - name: http
      port: 80
      targetPort: 80
    

az functionapp deployment source config-zip -g Network -n Astrella --src functions.zip

Publish-AzWebapp -ResourceGroupName Network -Name Astrella -ArchivePath functions.zip