apiVersion: apps/v1
kind: Deployment
metadata: 
  app: backend-restapp
  tier: backend
spec:
  replicas: 0
  selector:
    matchLabels:
      app: backend-restapp
  template:
    metadata:
      labels:
        app: backend-restapp
        tier: backend
    spec:
      containers:
        - name: backend-restapp
          image: stacksimplify/kube-helloworld:1.0.0
          ports:
            - containerPort: 8080